CPP_SRC = config.cpp buffer.cpp color.cpp countsrf.cpp cursor.cpp font.cpp fontasci.cpp \
          fontunic.cpp fonttex.cpp frame.cpp dlcache.cpp rgb.cpp \
          info.cpp light.cpp lightm.cpp material.cpp mcubes.cpp project.cpp viewport.cpp \
          zplane.cpp zvis.cpp matrix.cpp colmap.cpp raster.cpp texture.cpp error.cpp
GLT_HOME = ../..
INCLUDE  = -I$(GLT_HOME)/src/png
ARCHIVE = libglt.a

default: lib

include $(GLT_HOME)/gcc/Makefile.inc

