
#
# Subdirectories are recursed in this order - be careful to
# order things according to link dependencies.  (Programs
# should go last)
#

# CPW Doesn't work on Linux yet

SUBDIRS = glt misc math mesh node glutm fonts zlib unifont png csg glui prc program

default: recurse

include ../gcc/Makefile.inc



