#my make file for my nehe thingy
LIBS="-lSDL -lGL -lGLU -lSDL_image"

all: pong

clean:
	rm -f *.o pong

pong: pong.cpp
	g++ -o $@ -lSDL -lGL -lGLU -lSDL_image $<	#I can't remember what any of these symbols do @.@
