CPP_SRC = 	path.cpp matrix4.cpp plane.cpp point.cpp round.cpp vector3.cpp random.cpp \
		bbox.cpp volume.cpp umatrix.cpp
GLT_HOME = ../..
INCLUDE  =
ARCHIVE = libglt.a

default: lib

include $(GLT_HOME)/gcc/Makefile.inc
