CPP_SRC = config.cpp main.cpp master.cpp menu.cpp raypp.cpp window.cpp winexam.cpp winiv.cpp shape.cpp robot.cpp axes.cpp
GLT_HOME = ../..
INCLUDE  = 
ARCHIVE = libglutm.a
SUBDIRS = # example

default: lib

include $(GLT_HOME)/gcc/Makefile.inc

