CPP_SRC = blend.cpp fade.cpp interp.cpp line.cpp polygon.cpp shape.cpp shapes.cpp text.cpp \
	  dlist.cpp tiled.cpp histogrm.cpp field.cpp fields.cpp fieldmen.cpp starfld.cpp \
	  skybox.cpp skyspher.cpp registry.cpp

GLT_HOME = ../..
INCLUDE  =
ARCHIVE = libglt.a

default: lib

include $(GLT_HOME)/gcc/Makefile.inc
