#my make file for my nehe thingy
LIBS="-lSDL -lGL -lGLU -lSDL_image"

all: nehe

clean:
	rm -f *.o nehe

nehe: nehe.cpp
	g++ -o $@ -lSDL -lGL -lGLU -lSDL_image $<	#I can't remember what any of these symbols do @.@
