C_SRC    = adler32.c compress.c crc32.c deflate.c gzio.c infblock.c \
           infcodes.c inffast.c inflate.c inftrees.c infutil.c \
           trees.c uncompr.c zutil.c
GLT_HOME = ../..
INCLUDE  =
ARCHIVE = libz.a

default: lib

include $(GLT_HOME)/gcc/Makefile.inc





